import Link from "next/link";
import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { requireAuth } from "@/lib/auth";
import { toScoreCardView } from "@/lib/db";
import { PrintButton } from "@/components/PrintButton";

export const dynamic = "force-dynamic";

export default async function ReportPage({ params }: { params: Promise<{ projectId: string }> }) {
  await requireAuth();
  const { projectId } = await params;

  const project = await prisma.project.findUnique({
    where: { id: projectId },
    include: {
      candidates: {
        include: { scoreCard: true, outreachDraft: true },
      },
    },
  });
  if (!project) return notFound();

  const scored = project.candidates
    .filter((c) => c.scoreCard)
    .map((c) => ({ ...c, score: c.scoreCard ? toScoreCardView(c.scoreCard) : null }))
    .sort((a, b) => (b.score?.totalScore ?? 0) - (a.score?.totalScore ?? 0));

  const A = scored.filter((c) => c.score?.tier === "A");
  const B = scored.filter((c) => c.score?.tier === "B");
  const C = scored.filter((c) => c.score?.tier === "C");

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-start justify-between gap-3 print:hidden">
        <div>
          <h1 className="text-2xl font-semibold tracking-tight">Report</h1>
          <p className="mt-1 text-sm text-slate-600">
            Printable HTML report (use your browser’s Print to PDF).
          </p>
        </div>
        <div className="flex flex-wrap gap-2">
          <PrintButton />
          <Link href={`/projects/${projectId}/results`} className="rounded-md px-2 py-1 text-xs hover:bg-slate-100">
            Back to results
          </Link>
        </div>
      </div>

      <article className="prose prose-slate max-w-none">
        <header>
          <h2 className="m-0">{project.name}</h2>
          <p className="m-0 text-sm text-slate-600">
            Generated by QM License Finder Prototype v0.1 — evidence is best-effort; verify all proof points.
          </p>
        </header>

        <section>
          <h3>A-tier (client-ready shortlist)</h3>
          {A.length ? A.map((c) => <ReportCandidate key={c.id} c={c} />) : <p>(None yet)</p>}
        </section>

        <section>
          <h3>B-tier (good fits missing an element)</h3>
          {B.length ? B.map((c) => <ReportCandidate key={c.id} c={c} />) : <p>(None yet)</p>}
        </section>

        <section>
          <h3>C-tier (wildcards)</h3>
          {C.length ? C.map((c) => <ReportCandidate key={c.id} c={c} />) : <p>(None yet)</p>}
        </section>

        <hr />
        <p className="text-xs text-slate-500">
          Notes: This pre‑MVP does not use a search API. Where sources are not attached, proof points are listed as “to_verify.”
        </p>
      </article>
    </div>
  );
}

function ReportCandidate({ c }: { c: any }) {
  const score = c.score;
  return (
    <div className="break-inside-avoid rounded-lg border border-slate-200 p-3">
      <div className="flex items-baseline justify-between gap-3">
        <div>
          <div className="font-semibold">{c.name}</div>
          {c.website ? <div className="text-xs text-slate-600">{c.website}</div> : null}
        </div>
        <div className="text-xs text-slate-600">
          Tier {score?.tier} · Score {score?.totalScore} · Evidence {score?.confidence}
        </div>
      </div>

      <div className="mt-2">
        <div className="text-xs font-semibold text-slate-700">Rationale</div>
        <ul className="mt-1 list-disc pl-5 text-sm">
          {(score?.rationaleBullets ?? []).map((b: string, i: number) => (
            <li key={i}>{b}</li>
          ))}
        </ul>
      </div>

      <div className="mt-2">
        <div className="text-xs font-semibold text-slate-700">Proof points</div>
        <ul className="mt-1 list-disc pl-5 text-sm">
          {(score?.proofPoints ?? []).map((p: any, i: number) => (
            <li key={i}>
              {p.text} <span className="text-xs text-slate-500">({p.supportType})</span>
            </li>
          ))}
        </ul>
      </div>

      {score?.flags?.length ? (
        <div className="mt-2">
          <div className="text-xs font-semibold text-slate-700">Flags</div>
          <ul className="mt-1 list-disc pl-5 text-sm">
            {score.flags.map((f: string, i: number) => (
              <li key={i}>{f}</li>
            ))}
          </ul>
        </div>
      ) : null}

      {score?.disqualifiers?.length ? (
        <div className="mt-2">
          <div className="text-xs font-semibold text-slate-700">Disqualifiers</div>
          <ul className="mt-1 list-disc pl-5 text-sm">
            {score.disqualifiers.map((d: string, i: number) => (
              <li key={i}>{d}</li>
            ))}
          </ul>
        </div>
      ) : null}

      <div className="mt-2">
        <div className="text-xs font-semibold text-slate-700">Next step</div>
        <div className="mt-1 text-sm">{score?.nextStep}</div>
      </div>

      {c.outreachDraft ? (
        <div className="mt-3 rounded-md border border-slate-200 bg-slate-50 p-2">
          <div className="text-xs font-semibold text-slate-700">Outreach draft (no sending)</div>
          <div className="mt-1 text-xs text-slate-500">Subject</div>
          <div className="text-sm">{c.outreachDraft.subject}</div>
          <div className="mt-2 text-xs text-slate-500">Body</div>
          <pre className="whitespace-pre-wrap text-sm">{c.outreachDraft.body}</pre>
        </div>
      ) : null}
    </div>
  );
}
